"""initial schema

Revision ID: 5df9079cea83
Revises: 
Create Date: 2026-09-13 00:42:34.542012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5df9079cea83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenities')),
    sa.UniqueConstraint('code', name=op.f('uq_amenities_code')),
    sa.UniqueConstraint('name', name=op.f('uq_amenities_name'))
    )
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('applies_to', sa.Enum('USER', 'PROPERTY', 'BOTH', name='document_applies_to'), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types')),
    sa.UniqueConstraint('code', name=op.f('uq_document_types_code'))
    )
    op.create_table('property_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('RESIDENTIAL', 'LAND', 'COMMERCIAL', 'PG', name='property_category'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_types')),
    sa.UniqueConstraint('code', name=op.f('uq_property_types_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('room_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bedrooms', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_configurations')),
    sa.UniqueConstraint('code', name=op.f('uq_room_configurations_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('kyc_status', sa.Enum('NOT_SUBMITTED', 'PENDING', 'VERIFIED', 'REJECTED', name='kyc_status'), server_default='NOT_SUBMITTED', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_kyc_status', 'users', ['kyc_status'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'WHATSAPP', name='otp_channel'), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTRATION', 'LOGIN', 'PHONE_VERIFY', 'EMAIL_VERIFY', 'PASSWORD_RESET', name='otp_purpose'), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_verifications'))
    )
    op.create_index('ix_otp_identifier_purpose', 'otp_verifications', ['identifier', 'purpose'], unique=False)
    op.create_index('ix_otp_user_id', 'otp_verifications', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('listing_type', sa.Enum('RENT', 'SALE', 'PG', 'SHARED', name='listing_type'), nullable=False),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.Column('room_configuration_id', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.SmallInteger(), nullable=True),
    sa.Column('carpet_area_sqft', sa.Integer(), nullable=True),
    sa.Column('built_up_area_sqft', sa.Integer(), nullable=True),
    sa.Column('plot_area_sqft', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.SmallInteger(), nullable=True),
    sa.Column('total_floors', sa.SmallInteger(), nullable=True),
    sa.Column('furnishing', sa.Enum('UNFURNISHED', 'SEMI_FURNISHED', 'FULLY_FURNISHED', name='furnishing'), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('security_deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('maintenance_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_negotiable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'PAUSED', 'RENTED', 'SOLD', 'EXPIRED', 'REJECTED', name='property_status'), server_default='DRAFT', nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'RECENTLY_VERIFIED', 'EXPIRING', 'UNVERIFIED', 'EXPIRED', name='availability_status'), server_default='UNVERIFIED', nullable=False),
    sa.Column('availability_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trust_score', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_owner_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extra_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'DRAFT' OR (listing_type = 'SALE' AND sale_price IS NOT NULL) OR (listing_type <> 'SALE' AND rent_amount IS NOT NULL)", name=op.f('ck_properties_price_required_when_listed')),
    sa.CheckConstraint('rent_amount IS NULL OR rent_amount >= 0', name=op.f('ck_properties_rent_nonneg')),
    sa.CheckConstraint('sale_price IS NULL OR sale_price >= 0', name=op.f('ck_properties_sale_price_nonneg')),
    sa.CheckConstraint('security_deposit IS NULL OR security_deposit >= 0', name=op.f('ck_properties_deposit_nonneg')),
    sa.CheckConstraint('trust_score BETWEEN 0 AND 100', name=op.f('ck_properties_trust_score_range')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_properties_owner_id_users')),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], name=op.f('fk_properties_property_type_id_property_types')),
    sa.ForeignKeyConstraint(['room_configuration_id'], ['room_configurations.id'], name=op.f('fk_properties_room_configuration_id_room_configurations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_index('ix_properties_available_from', 'properties', ['available_from'], unique=False)
    op.create_index('ix_properties_created_at', 'properties', ['created_at'], unique=False)
    op.create_index('ix_properties_listing_type', 'properties', ['listing_type'], unique=False)
    op.create_index('ix_properties_owner_id', 'properties', ['owner_id'], unique=False)
    op.create_index('ix_properties_property_type_id', 'properties', ['property_type_id'], unique=False)
    op.create_index('ix_properties_rent_amount', 'properties', ['rent_amount'], unique=False)
    op.create_index('ix_properties_sale_price', 'properties', ['sale_price'], unique=False)
    op.create_index('ix_properties_status', 'properties', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('property_amenities',
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_property_amenities_amenity_id_amenities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_amenities_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'amenity_id', name=op.f('pk_property_amenities'))
    )
    op.create_table('property_availability_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'EXPIRED', name='availability_event_status'), nullable=False),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('confirmation_method', sa.Enum('OWNER_APP', 'PHONE', 'WHATSAPP', 'ADMIN', name='confirmation_method'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_property_availability_history_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_availability_history_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_availability_history'))
    )
    op.create_index('ix_property_availability_history_confirmed_at', 'property_availability_history', ['confirmed_at'], unique=False)
    op.create_index('ix_property_availability_history_property_id', 'property_availability_history', ['property_id'], unique=False)
    op.create_table('property_inquiries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('contact_method', sa.Enum('PHONE', 'WHATSAPP', 'EMAIL', 'PLATFORM', name='contact_method'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'RESPONDED', 'CLOSED', name='inquiry_status'), server_default='NEW', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_property_inquiries_buyer_id_users')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_property_inquiries_owner_id_users')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_inquiries_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_inquiries'))
    )
    op.create_index('ix_property_inquiries_buyer_id', 'property_inquiries', ['buyer_id'], unique=False)
    op.create_index('ix_property_inquiries_owner_id', 'property_inquiries', ['owner_id'], unique=False)
    op.create_index('ix_property_inquiries_property_id', 'property_inquiries', ['property_id'], unique=False)
    op.create_index('ix_property_inquiries_status', 'property_inquiries', ['status'], unique=False)
    op.create_table('property_locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=60), server_default='India', nullable=False),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_property_locations_lat_range')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_property_locations_lng_range')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_locations_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_locations')),
    sa.UniqueConstraint('property_id', name=op.f('uq_property_locations_property_id'))
    )
    op.create_index('ix_property_locations_city', 'property_locations', ['city'], unique=False)
    op.create_index('ix_property_locations_city_locality', 'property_locations', ['city', 'locality'], unique=False)
    op.create_index('ix_property_locations_locality', 'property_locations', ['locality'], unique=False)
    op.create_index('ix_property_locations_pincode', 'property_locations', ['pincode'], unique=False)
    op.create_index('ix_property_locations_state', 'property_locations', ['state'], unique=False)
    op.create_table('property_media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'FLOOR_PLAN', 'VIRTUAL_TOUR', name='media_type'), server_default='IMAGE', nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_media_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_media'))
    )
    op.create_index('ix_property_media_property_id', 'property_media', ['property_id'], unique=False)
    op.create_index('uq_property_media_one_primary', 'property_media', ['property_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('property_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('reported_by', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Enum('FAKE_LISTING', 'ALREADY_RENTED', 'ALREADY_SOLD', 'WRONG_INFORMATION', 'BROKER', 'DUPLICATE', 'SCAM', 'INAPPROPRIATE', 'OTHER', name='report_reason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='report_status'), server_default='OPEN', nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_reports_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_property_reports_reported_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_property_reports_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_reports'))
    )
    op.create_index('ix_property_reports_property_id', 'property_reports', ['property_id'], unique=False)
    op.create_index('ix_property_reports_status', 'property_reports', ['status'], unique=False)
    op.create_table('property_status_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_property_status_history_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_status_history_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_status_history'))
    )
    op.create_index('ix_property_status_history_property_id', 'property_status_history', ['property_id'], unique=False)
    op.create_table('property_verifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('verification_type', sa.Enum('OWNER', 'PHONE', 'AVAILABILITY', 'PROPERTY', 'DOCUMENT', name='verification_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', 'EXPIRED', name='verification_status'), server_default='PENDING', nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_verifications_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_property_verifications_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_verifications'))
    )
    op.create_index('ix_property_verifications_property_id', 'property_verifications', ['property_id'], unique=False)
    op.create_index('ix_property_verifications_status', 'property_verifications', ['status'], unique=False)
    op.create_table('property_views',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_hash', sa.String(length=255), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_views_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_property_views_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_views'))
    )
    op.create_index('ix_property_views_property_id', 'property_views', ['property_id'], unique=False)
    op.create_index('ix_property_views_user_id', 'property_views', ['user_id'], unique=False)
    op.create_index('ix_property_views_viewed_at', 'property_views', ['viewed_at'], unique=False)
    op.create_table('saved_properties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_saved_properties_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_properties_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_properties')),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_saved_user_property')
    )
    op.create_index('ix_saved_properties_user_id', 'saved_properties', ['user_id'], unique=False)
    op.create_table('verification_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='document_status'), server_default='PENDING', nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_verification_documents_document_type_id_document_types')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_verification_documents_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_documents_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_verification_documents_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_documents'))
    )
    op.create_index('ix_verification_documents_property_id', 'verification_documents', ['property_id'], unique=False)
    op.create_index('ix_verification_documents_status', 'verification_documents', ['status'], unique=False)
    op.create_index('ix_verification_documents_user_id', 'verification_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # ---- Seed data: roles, taxonomies, amenities, document types ----
    roles = sa.table(
        'roles',
        sa.column('code', sa.String), sa.column('name', sa.String),
    )
    op.bulk_insert(roles, [
        {'code': 'ADMIN', 'name': 'Admin'},
        {'code': 'SELLER', 'name': 'Seller'},
        {'code': 'BUYER', 'name': 'Buyer'},
    ])

    property_category_enum = postgresql.ENUM(
        'RESIDENTIAL', 'LAND', 'COMMERCIAL', 'PG',
        name='property_category', create_type=False,
    )
    property_types = sa.table(
        'property_types',
        sa.column('code', sa.String), sa.column('name', sa.String),
        sa.column('category', property_category_enum),
        sa.column('sort_order', sa.SmallInteger),
    )
    op.bulk_insert(property_types, [
        {'code': 'APARTMENT', 'name': 'Apartment / Flat', 'category': 'RESIDENTIAL', 'sort_order': 1},
        {'code': 'VILLA', 'name': 'Villa', 'category': 'RESIDENTIAL', 'sort_order': 2},
        {'code': 'INDEPENDENT_HOUSE', 'name': 'Independent House', 'category': 'RESIDENTIAL', 'sort_order': 3},
        {'code': 'BUILDER_FLOOR', 'name': 'Builder Floor', 'category': 'RESIDENTIAL', 'sort_order': 4},
        {'code': 'PENTHOUSE', 'name': 'Penthouse', 'category': 'RESIDENTIAL', 'sort_order': 5},
        {'code': 'RESIDENTIAL_PLOT', 'name': 'Residential Plot', 'category': 'LAND', 'sort_order': 10},
        {'code': 'COMMERCIAL_PLOT', 'name': 'Commercial Plot', 'category': 'LAND', 'sort_order': 11},
        {'code': 'AGRICULTURAL_LAND', 'name': 'Agricultural Land', 'category': 'LAND', 'sort_order': 12},
        {'code': 'OFFICE_SPACE', 'name': 'Office Space', 'category': 'COMMERCIAL', 'sort_order': 20},
        {'code': 'SHOP', 'name': 'Shop / Retail', 'category': 'COMMERCIAL', 'sort_order': 21},
        {'code': 'SHOWROOM', 'name': 'Showroom', 'category': 'COMMERCIAL', 'sort_order': 22},
        {'code': 'WAREHOUSE', 'name': 'Warehouse / Godown', 'category': 'COMMERCIAL', 'sort_order': 23},
        {'code': 'PG_ACCOMMODATION', 'name': 'PG Accommodation', 'category': 'PG', 'sort_order': 30},
        {'code': 'SHARED_ROOM', 'name': 'Shared Room', 'category': 'PG', 'sort_order': 31},
        {'code': 'CO_LIVING', 'name': 'Co-living Space', 'category': 'PG', 'sort_order': 32},
    ])

    room_configurations = sa.table(
        'room_configurations',
        sa.column('code', sa.String), sa.column('name', sa.String),
        sa.column('bedrooms', sa.SmallInteger), sa.column('sort_order', sa.SmallInteger),
    )
    op.bulk_insert(room_configurations, [
        {'code': '1RK', 'name': '1 RK', 'bedrooms': 0, 'sort_order': 1},
        {'code': 'STUDIO', 'name': 'Studio', 'bedrooms': 0, 'sort_order': 2},
        {'code': '1BHK', 'name': '1 BHK', 'bedrooms': 1, 'sort_order': 3},
        {'code': '2BHK', 'name': '2 BHK', 'bedrooms': 2, 'sort_order': 4},
        {'code': '3BHK', 'name': '3 BHK', 'bedrooms': 3, 'sort_order': 5},
        {'code': '4BHK', 'name': '4 BHK', 'bedrooms': 4, 'sort_order': 6},
        {'code': '5PLUS_BHK', 'name': '5+ BHK', 'bedrooms': 5, 'sort_order': 7},
    ])

    amenities = sa.table(
        'amenities',
        sa.column('code', sa.String), sa.column('name', sa.String),
        sa.column('sort_order', sa.SmallInteger),
    )
    op.bulk_insert(amenities, [
        {'code': 'PARKING', 'name': 'Parking', 'sort_order': 1},
        {'code': 'LIFT', 'name': 'Lift', 'sort_order': 2},
        {'code': 'POWER_BACKUP', 'name': 'Power Backup', 'sort_order': 3},
        {'code': 'GYM', 'name': 'Gym', 'sort_order': 4},
        {'code': 'SWIMMING_POOL', 'name': 'Swimming Pool', 'sort_order': 5},
        {'code': 'SECURITY_24X7', 'name': '24x7 Security', 'sort_order': 6},
        {'code': 'WIFI', 'name': 'WiFi', 'sort_order': 7},
        {'code': 'AIR_CONDITIONING', 'name': 'Air Conditioning', 'sort_order': 8},
        {'code': 'BALCONY', 'name': 'Balcony', 'sort_order': 9},
        {'code': 'GATED_COMMUNITY', 'name': 'Gated Community', 'sort_order': 10},
        {'code': 'CCTV', 'name': 'CCTV', 'sort_order': 11},
        {'code': 'CLUB_HOUSE', 'name': 'Club House', 'sort_order': 12},
        {'code': 'CHILDRENS_PLAY_AREA', 'name': "Children's Play Area", 'sort_order': 13},
        {'code': 'WATER_SUPPLY_24X7', 'name': '24x7 Water Supply', 'sort_order': 14},
        {'code': 'PET_FRIENDLY', 'name': 'Pet Friendly', 'sort_order': 15},
    ])

    applies_to_enum = postgresql.ENUM(
        'USER', 'PROPERTY', 'BOTH',
        name='document_applies_to', create_type=False,
    )
    document_types = sa.table(
        'document_types',
        sa.column('code', sa.String), sa.column('name', sa.String),
        sa.column('applies_to', applies_to_enum),
    )
    op.bulk_insert(document_types, [
        {'code': 'AADHAAR_CARD', 'name': 'Aadhaar Card', 'applies_to': 'USER'},
        {'code': 'PAN_CARD', 'name': 'PAN Card', 'applies_to': 'USER'},
        {'code': 'PASSPORT', 'name': 'Passport', 'applies_to': 'USER'},
        {'code': 'DRIVING_LICENSE', 'name': 'Driving License', 'applies_to': 'USER'},
        {'code': 'PROPERTY_OWNERSHIP_PROOF', 'name': 'Property Ownership Proof', 'applies_to': 'BOTH'},
        {'code': 'SALE_DEED', 'name': 'Sale Deed', 'applies_to': 'PROPERTY'},
        {'code': 'OTHER', 'name': 'Other', 'applies_to': 'BOTH'},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_documents_user_id', table_name='verification_documents')
    op.drop_index('ix_verification_documents_status', table_name='verification_documents')
    op.drop_index('ix_verification_documents_property_id', table_name='verification_documents')
    op.drop_table('verification_documents')
    op.drop_index('ix_saved_properties_user_id', table_name='saved_properties')
    op.drop_table('saved_properties')
    op.drop_index('ix_property_views_viewed_at', table_name='property_views')
    op.drop_index('ix_property_views_user_id', table_name='property_views')
    op.drop_index('ix_property_views_property_id', table_name='property_views')
    op.drop_table('property_views')
    op.drop_index('ix_property_verifications_status', table_name='property_verifications')
    op.drop_index('ix_property_verifications_property_id', table_name='property_verifications')
    op.drop_table('property_verifications')
    op.drop_index('ix_property_status_history_property_id', table_name='property_status_history')
    op.drop_table('property_status_history')
    op.drop_index('ix_property_reports_status', table_name='property_reports')
    op.drop_index('ix_property_reports_property_id', table_name='property_reports')
    op.drop_table('property_reports')
    op.drop_index('uq_property_media_one_primary', table_name='property_media', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_property_media_property_id', table_name='property_media')
    op.drop_table('property_media')
    op.drop_index('ix_property_locations_state', table_name='property_locations')
    op.drop_index('ix_property_locations_pincode', table_name='property_locations')
    op.drop_index('ix_property_locations_locality', table_name='property_locations')
    op.drop_index('ix_property_locations_city_locality', table_name='property_locations')
    op.drop_index('ix_property_locations_city', table_name='property_locations')
    op.drop_table('property_locations')
    op.drop_index('ix_property_inquiries_status', table_name='property_inquiries')
    op.drop_index('ix_property_inquiries_property_id', table_name='property_inquiries')
    op.drop_index('ix_property_inquiries_owner_id', table_name='property_inquiries')
    op.drop_index('ix_property_inquiries_buyer_id', table_name='property_inquiries')
    op.drop_table('property_inquiries')
    op.drop_index('ix_property_availability_history_property_id', table_name='property_availability_history')
    op.drop_index('ix_property_availability_history_confirmed_at', table_name='property_availability_history')
    op.drop_table('property_availability_history')
    op.drop_table('property_amenities')
    op.drop_table('user_roles')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_properties_status', table_name='properties')
    op.drop_index('ix_properties_sale_price', table_name='properties')
    op.drop_index('ix_properties_rent_amount', table_name='properties')
    op.drop_index('ix_properties_property_type_id', table_name='properties')
    op.drop_index('ix_properties_owner_id', table_name='properties')
    op.drop_index('ix_properties_listing_type', table_name='properties')
    op.drop_index('ix_properties_created_at', table_name='properties')
    op.drop_index('ix_properties_available_from', table_name='properties')
    op.drop_table('properties')
    op.drop_index('ix_otp_user_id', table_name='otp_verifications')
    op.drop_index('ix_otp_identifier_purpose', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_kyc_status', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('room_configurations')
    op.drop_table('roles')
    op.drop_table('property_types')
    op.drop_table('document_types')
    op.drop_table('amenities')
    # ### end Alembic commands ###

    for enum_name in (
        'listing_type', 'property_category', 'furnishing', 'property_status',
        'availability_status', 'media_type', 'kyc_status', 'document_status',
        'document_applies_to', 'verification_type', 'verification_status',
        'availability_event_status', 'confirmation_method', 'contact_method',
        'inquiry_status', 'report_reason', 'report_status', 'otp_channel',
        'otp_purpose',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
